// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("product_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("valid_from")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("valid_to")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            price = 500f,
                            product_name = "PlayStation 5",
                            valid_from = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            price = 400f,
                            product_name = "xBox One",
                            valid_from = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            price = 1500f,
                            product_name = "Smart TV OLED",
                            valid_from = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            price = 500f,
                            product_name = "Tastatura RGB",
                            valid_from = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            price = 1500f,
                            product_name = "Monitor 4k",
                            valid_from = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
